import Header from './components';
import Footer from './components';

export const metadata = {
  title: "A leading agency for creative technology.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en-GB">
      <body className='scroll-smooth' dir='ltr'>
        <div>
          <Header role='header' />
            <main>{children}</main>
          <Footer role='footer' />
        </div>
      </body>
    </html>
  );
}
