# This workflow will do a clean installation of node dependencies, cache/restore them, and build the source code

name: Node.js CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # Node.js version 22.x only

    steps:
      - uses: actions/checkout@v4 # Latest stable version of actions/checkout
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # Latest stable version of actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: node -v # Confirm the Node.js version
      - run: npm cache clean --force # Clear npm cache
      - run: npm ci --loglevel verbose # Install dependencies with verbose logging
      - run: npm run build --loglevel verbose # Build the project with verbose logging
